### ISSUE TITLE
@throws Namespace Problem

### ISSUE THREAD

**Issue by rodnaph** [boxuk/codingstandards#2]
When checking namespace annotations, using a backslash to indicate the root namespace causes the sniff to fail when it's actually ok.  Example:

<pre>
/**
 * @throws \Exception
 */
public function foo() {
  throw new \Exception();
}
</pre>

**Comment by gavD** [comment]
OK, I'll add a unit test to coding standards and will investigate

**Comment by gavD** [comment]
Patch sent to http://pear.php.net/bugs/bug.php?id=18624

**Comment by gavD** [comment]
Closing
