### ISSUE TITLE
@param int type

### ISSUE THREAD

**Issue by rodnaph** [boxuk/codingstandards#5]
# minor-issue

Currently the allowed scalar param types are 'integer', 'float', 'string' and 'bool'.

https://github.com/boxuk/codingstandards/blob/master/PHP/BoxUK/Sniffs/Commenting/FunctionCommentSniff.php#L397

This doesn't allow use of 'int' for integers.

So, RFC really...  Should we force 'integer' over 'int'?  PHP usually refers to integer in its docs, but int seems preferred by PHPDoc, and php functions support both using is_int and is_integer.  I say either support both, or force 'int' as it's phpdoc's preferred and we already use bool not boolean.

**Comment by gavD** [comment]
FIX IT RODDERS
